on:
  push:
    branches:
      - main
  pull_request:

name: Integration Tests

jobs:
  ## Integration tests ##
  integration-rattler-dry-run:
    # NOTES:
    #   - `pipefail` must be enabled in order get the exit code from the conda-recipe-manager commands when
    #     the output is piped into `tee`
    #   - We setup empty environment variables like `PREFIX` to suppress rattler-build dry-run failures that are
    #     specific to the expected build environment. Such a failure does not reflect our ability to convert recipe
    #     files successfully. We should remove these environment changes if/when rattler-build gives us another way to
    #     validate recipe files.
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Test on ${{ matrix.test-directory }}
    strategy:
      fail-fast: false
      matrix:
        test-directory:
          - anaconda_recipes_01
          - bioconda_recipes_01
          - bioconda_recipes_02
          - bioconda_recipes_03
          - bioconda_recipes_04
        include:
          - test-directory: anaconda_recipes_01
            convert-success: 0.90
            rattler-success: 0.75
          - test-directory: bioconda_recipes_01
            convert-success: 0.85
            rattler-success: 0.70
          - test-directory: bioconda_recipes_02
            convert-success: 0.85
            rattler-success: 0.75
          - test-directory: bioconda_recipes_03
            convert-success: 0.85
            rattler-success: 0.55
          - test-directory: bioconda_recipes_04
            convert-success: 0.85
            rattler-success: 0.60
          # 2,000 randomly selected conda-forge recipes
          - test-directory: conda_forge_recipes_01
            convert-success: 0.90
            rattler-success: 0.70
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: conda-incubator/conda-recipe-manager-test-data
          path: test_data
          sparse-checkout: recipes_v0/${{ matrix.test-directory }}
      - uses: ./.github/actions/setup-env
        with:
          python-version: "3.11"
      - name: Convert recipes and dry-run rattler-build
        run: |
          source $CONDA/bin/activate
          conda activate conda-recipe-manager
          conda install -y -c conda-forge rattler-build
          mkdir -p logs
          set -o pipefail
          export PREFIX=""
          export RECIPE_DIR=""
          conda-recipe-manager \
            convert -t -m ${{ matrix.convert-success }} -o recipe.yaml test_data/recipes_v0/${{ matrix.test-directory }} \
            | tee logs/convert_${{ matrix.test-directory }}.log
          conda-recipe-manager \
            rattler-bulk-build -t -m ${{ matrix.rattler-success }} test_data/recipes_v0/${{ matrix.test-directory }} --render-only \
            | tee logs/rbb_${{ matrix.test-directory }}.log
      - uses: actions/upload-artifact@v4
        with:
          name: integration-logs-${{ matrix.test-directory }}
          path: logs/*.log
  integration-dry-run-final-results:
    runs-on: ubuntu-latest
    name: Integration Testing Final Report
    needs: [integration-rattler-dry-run]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-env
        with:
          python-version: "3.11"
      - name: Make artifact directory
        run: mkdir -p logs
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: logs/
      - name: Integration Testing Report
        run: |
          source $CONDA/bin/activate
          conda activate conda-recipe-manager
          set -o pipefail
          scripts/parse_ci_output.py logs/ | tee report.json
          echo -e "Integration Report:\n\`\`\`json\n" >> ${GITHUB_STEP_SUMMARY}
          cat report.json >> ${GITHUB_STEP_SUMMARY}
          echo -e "\n\`\`\`" >> ${GITHUB_STEP_SUMMARY}
  integration-rattler-build:
    # NOTES:
    #  - `crm rattler-bulk-build` is used over `rattler-build` so that all recipe files are automatically found in the
    #    checked-out feedstock directory.
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build ${{ matrix.feedstock }}
    strategy:
      fail-fast: false
      matrix:
        feedstock:
          - conda-forge/types-toml-feedstock
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ matrix.feedstock }}
          path: feedstock
      - uses: ./.github/actions/setup-env
        with:
          python-version: "3.11"
      - name: Convert recipes from a feedstock repo and run a build
        continue-on-error: true
        run: |
          source $CONDA/bin/activate
          conda activate conda-recipe-manager
          conda install -y -c conda-forge rattler-build
          set -o pipefail
          conda-recipe-manager convert --ignore-warnings -o recipe.yaml feedstock
          conda-recipe-manager rattler-bulk-build feedstock
